### PR TITLE
feat: optimistic upvotes, remove post upvote redirect, style fixes

### LINKED ISSUE #14: Project's card content flowing out of the box
### 👟 Reproduction steps

Go to the link https://builtwith.appwrite.io/search/?useCase=demo-app
And the first project's card with the name "Teacher-Student Ratio Calculator" has its content flowing out of the box.

### 👍 Expected behavior

The card's content should be in the box only and should wrap if the space is not available. 

### 👎 Actual Behavior

The card's content is not wrapped and flowing out of the box.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by loks0n**
- Updates upvote counter optimistically
- Removes redirect to project detail page after upvote
- Fixes #14 
- Fixes search page (/search?platform=web) project image overflow bug on Safari (see image below)
safari bug
- Persist light/dark theme selection on page reload

### CODE REVIEW

File: src/components/blocks/Upvote.tsx [hunk 1]
```diff
@@ -1,88 +1,86 @@
...
-      isPrimary = false;
+    try {
+      const res = await AppwriteService.upvoteProject(props.projectId);
+      if (accountContext.value) {
+        upvoteContext.value = await AppwriteService.listUserUpvotes(
+          accountContext.value.$id
+        );
+      }
+      votesServer.value = res.votes;
+    } catch (err: any) {
```
Comment (TorstenDittmann) [inline src/components/blocks/Upvote.tsx:60]: `any` is always kinda meh. I would start out with `unknown` 

```suggestion
    } catch (err: unknown) {
```

 If this comes from Appwrite, the SDK has an `AppwriteException` available as well 👍🏻

**Review by TorstenDittmann — APPROVED** [review]
